
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.WindowFocusListener;
import java.io.IOException;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Home extends javax.swing.JFrame implements ActionListener, WindowFocusListener {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setExtendedState(NewEmpolyee.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(this);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/room.png"))); // NOI18N
        jButton1.setText("Manage Room");
        jButton1.addActionListener(this);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 310, 50));

        jButton2.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new student.png"))); // NOI18N
        jButton2.setText("New Student");
        jButton2.addActionListener(this);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 310, 40));

        jButton3.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update & Delete Student.png"))); // NOI18N
        jButton3.setText("Update Students");
        jButton3.addActionListener(this);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 310, 40));

        jButton4.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/all student living.png"))); // NOI18N
        jButton4.setText("All Students List");
        jButton4.addActionListener(this);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 310, 40));

        jButton5.setFont(new java.awt.Font("Bell MT", 3, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jButton5.setText("LOGOUT");
        jButton5.addActionListener(this);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));

        jButton6.setFont(new java.awt.Font("Bell MT", 3, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close.png"))); // NOI18N
        jButton6.setText("EXIT");
        jButton6.setToolTipText("");
        jButton6.addActionListener(this);
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, -1));

        jButton7.setFont(new java.awt.Font("Bell MT", 3, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shut Down.png"))); // NOI18N
        jButton7.setText("SHUTDOWN");
        jButton7.addActionListener(this);
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, -1, -1));

        jButton8.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fees_1.png"))); // NOI18N
        jButton8.setText("Student Fee");
        jButton8.addActionListener(this);
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 310, 40));

        jButton9.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new student.png"))); // NOI18N
        jButton9.setText("New Employee");
        jButton9.addActionListener(this);
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 310, 40));

        jButton10.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update & Delete Student.png"))); // NOI18N
        jButton10.setText("Update And Delete Employee");
        jButton10.addActionListener(this);
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 310, -1));

        jButton11.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fees.png"))); // NOI18N
        jButton11.setText("Employee Payment");
        jButton11.addActionListener(this);
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 310, 40));

        jButton12.setFont(new java.awt.Font("Bell MT", 3, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/all student living.png"))); // NOI18N
        jButton12.setText("Employee List");
        jButton12.addActionListener(this);
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 310, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homebg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1360, -1));

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButton1) {
            Home.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2) {
            Home.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton3) {
            Home.this.jButton3ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton4) {
            Home.this.jButton4ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton5) {
            Home.this.jButton5ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton6) {
            Home.this.jButton6ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton7) {
            Home.this.jButton7ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton8) {
            Home.this.jButton8ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton9) {
            Home.this.jButton9ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton10) {
            Home.this.jButton10ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton11) {
            Home.this.jButton11ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton12) {
            Home.this.jButton12ActionPerformed(evt);
        }
    }

    public void windowGainedFocus(java.awt.event.WindowEvent evt) {
        if (evt.getSource() == Home.this) {
            Home.this.formWindowGainedFocus(evt);
        }
    }

    public void windowLostFocus(java.awt.event.WindowEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setForeground(Color.red);
        jButton1.setBackground(new Color(255,255,255));
        new Manage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        jButton1.setForeground(new JButton().getForeground());
        jButton1.setBackground(new JButton().getBackground());
        
        jButton2.setForeground(new JButton().getForeground());
        jButton2.setBackground(new JButton().getBackground());
        
        jButton3.setForeground(new JButton().getForeground());
        jButton3.setBackground(new JButton().getBackground());
        
        jButton4.setForeground(new JButton().getForeground());
        jButton4.setBackground(new JButton().getBackground());
        
        jButton10.setForeground(new JButton().getForeground());
        jButton10.setBackground(new JButton().getBackground());
        
        jButton8.setForeground(new JButton().getForeground());
        jButton8.setBackground(new JButton().getBackground());
        
        jButton9.setForeground(new JButton().getForeground());
        jButton9.setBackground(new JButton().getBackground());
        
        jButton11.setForeground(new JButton().getForeground());
        jButton11.setBackground(new JButton().getBackground());
        
        jButton12.setForeground(new JButton().getForeground());
        jButton12.setBackground(new JButton().getBackground());
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int a;
        a = JOptionPane.showConfirmDialog(null,"Do You really want to Logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          int a;
        a = JOptionPane.showConfirmDialog(null,"Do You really want to Exit","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         int a;
        a = JOptionPane.showConfirmDialog(null,"Do You really want to ShutDown","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
             Runtime runtime = Runtime.getRuntime();
             try{
                Process proc=runtime.exec("shutdown -s -t 0");
             }
             catch(IOException e)
             {
               JOptionPane.showConfirmDialog(null, evt);
             }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setForeground(Color.red);
        jButton2.setBackground(new Color(255,255,255));
        new NewStudent().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.setForeground(Color.red);
        jButton3.setBackground(new Color(255,255,255));
        new Update().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setForeground(Color.red);
        jButton4.setBackground(new Color(255,255,255));
        new AllStudent().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         jButton10.setForeground(Color.red);
        jButton10.setBackground(new Color(255,255,255));
        new UpdateDeleteEmployee().setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jButton8.setForeground(Color.red);
        jButton8.setBackground(new Color(255,255,255));
        new StudentFee().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         jButton9.setForeground(Color.red);
        jButton9.setBackground(new Color(255,255,255));
        new NewEmpolyee().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         jButton11.setForeground(Color.red);
        jButton11.setBackground(new Color(255,255,255));
        new EmployeePayment().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         jButton12.setForeground(Color.red);
        jButton12.setBackground(new Color(255,255,255));
        new EmployeeList().setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
